const http = require('http');
const fs = require('fs');
const path = require('path');
const { WebSocketServer } = require('ws');

const PORT = process.env.PORT || 3000;
const DATA = path.join(__dirname, 'ranks.json');
let ranks = {};
try { ranks = JSON.parse(fs.readFileSync(DATA,'utf8')); } catch { ranks = {}; }
function saveRanks(){ try{fs.writeFileSync(DATA, JSON.stringify(ranks,null,2));}catch{} }
function rankFor(w){w=+w||0;if(w>=30)return 'Champion';if(w>=25)return 'Diamante';if(w>=20)return 'Platina';if(w>=15)return 'Ouro';if(w>=10)return 'Prata';if(w>=5)return 'Bronze';return 'Sem Rank';}
function rankColor(r){return ({'Sem Rank':'#fff','Bronze':'#cd7f32','Prata':'#c0c0c0','Ouro':'#ffd700','Platina':'#7ee6e8','Diamante':'#55b9ff','Champion':'#ff4d9d'})[r]||'#fff'}
const clients = new Map();
let waiting = null;
const rooms = new Map();
const SHOT_INTERVAL=2000;
function send(ws,o){if(ws.readyState===1)ws.send(JSON.stringify(o));}
function broadcast(room,o){for(const id of room.players){const c=clients.get(id);if(c)send(c.ws,o)}}
function makePlayer(ws,nick,wins){const id=Math.random().toString(36).slice(2,10);return {id,ws,nick:String(nick||'Player1').slice(0,16),wins:+wins||0,x:.5,hp:100,shield:0,lastShot:0,room:null};}
function match(a,b){const room={id:Math.random().toString(36).slice(2,9),players:[a.id,b.id]};rooms.set(room.id,room);a.room=room.id;b.room=room.id;a.x=.3;b.x=.7;a.hp=b.hp=100;a.shield=b.shield=0;send(a.ws,{type:'match',room:room.id,you:{x:a.x,hp:a.hp,shield:0},enemy:{x:b.x,hp:b.hp,nick:b.nick,shield:0,c:'#ff4050'}});send(b.ws,{type:'match',room:room.id,you:{x:b.x,hp:b.hp,shield:0},enemy:{x:a.x,hp:a.hp,nick:a.nick,shield:0,c:'#55b9ff'}});}
function leave(c){if(c.room){const r=rooms.get(c.room);if(r){for(const id of r.players){if(id!==c.id){const o=clients.get(id);if(o){send(o.ws,{type:'left'});o.room=null;o.shield=0;}}}rooms.delete(r.id)}c.room=null;}if(waiting===c)waiting=null;}
function hit(target,attacker,damage){if(target.shield>0){target.shield--;send(target.ws,{type:'hit',target:target.id,hp:target.hp,shield:target.shield,blocked:true});send(attacker.ws,{type:'enemyHit',blocked:true});return false;}target.hp=Math.max(0,target.hp-damage);send(target.ws,{type:'hit',target:target.id,hp:target.hp,shield:target.shield});send(attacker.ws,{type:'enemyHit'});if(target.hp<=0)finish(attacker,target);return true;}
function finish(winner,loser){const rw=(ranks[winner.nick]?.wins||winner.wins||0)+1;winner.wins=rw;ranks[winner.nick]={wins:rw,rank:rankFor(rw),rankColor:rankColor(rankFor(rw))};saveRanks();send(winner.ws,{type:'win',wins:rw,rank:rankFor(rw)});send(loser.ws,{type:'lose',wins:loser.wins||0,rank:rankFor(loser.wins||0)});const room=rooms.get(winner.room);if(room)rooms.delete(room.id);winner.room=null;loser.room=null;}
const server=http.createServer((req,res)=>{let u=req.url.split('?')[0];if(u==='/api/leaderboard'){const arr=Object.entries(ranks).map(([nick,v])=>({nick,...v})).sort((a,b)=>b.wins-a.wins).slice(0,5);res.writeHead(200,{'content-type':'application/json','access-control-allow-origin':'*'});res.end(JSON.stringify({online:[...clients.values()].length,players:arr}));return}if(u==='/api/player'&&req.method==='POST'){let body='';req.on('data',d=>body+=d);req.on('end',()=>{try{const p=JSON.parse(body);const nick=String(p.nick||'Player1').slice(0,16);const wins=Math.max(0,+p.wins||0);ranks[nick]={wins,rank:rankFor(wins),rankColor:rankColor(rankFor(wins)),level:+p.level||1,xp:+p.xp||0};saveRanks();res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify(ranks[nick]));}catch{res.writeHead(400);res.end('{}')}});return}if(u==='/'){res.writeHead(200,{'content-type':'text/html; charset=utf-8'});res.end(fs.readFileSync(path.join(__dirname,'index.html')));return}res.writeHead(404);res.end('Not found');});
const wss=new WebSocketServer({server});
wss.on('connection',ws=>{const c=makePlayer(ws,'Player1',0);clients.set(c.id,c);send(ws,{type:'welcome',id:c.id});ws.on('message',raw=>{let m;try{m=JSON.parse(raw)}catch{return}if(m.type==='join'){c.nick=String(m.nick||'Player1').slice(0,16);c.wins=+(ranks[c.nick]?.wins??m.wins??0);if(waiting&&waiting!==c){const a=waiting;waiting=null;match(a,c)}else if(!c.room){waiting=c;send(ws,{type:'waiting'})}}else if(m.type==='leave'){leave(c)}else if(m.type==='move'&&c.room){c.x=Math.max(.08,Math.min(.92,+m.x||.5));const r=rooms.get(c.room);if(r)for(const id of r.players)if(id!==c.id){const o=clients.get(id);if(o)send(o.ws,{type:'state',id:c.id,player:{x:c.x,hp:c.hp,shield:c.shield,nick:c.nick}})}}else if(m.type==='shoot'&&c.room){const now=Date.now();if(now-c.lastShot<SHOT_INTERVAL)return;c.lastShot=now;const r=rooms.get(c.room);if(!r)return;const enemy=clients.get(r.players.find(id=>id!==c.id));if(!enemy)return;send(enemy.ws,{type:'shot',id:c.id,x:c.x,damage:Math.min(25,+m.damage||10)});setTimeout(()=>{if(c.room===enemy.room)hit(enemy,c,Math.min(25,+m.damage||10));},260)}else if(m.type==='skill'&&c.room){const now=Date.now();if(now-c.lastShot<SHOT_INTERVAL)return;c.lastShot=now;const r=rooms.get(c.room);const enemy=clients.get(r.players.find(id=>id!==c.id));if(!enemy)return;for(let i=0;i<5;i++){const x=Math.max(.05,Math.min(.95,c.x+(i-2)*.035));send(enemy.ws,{type:'skill',id:c.id,x,damage:10});setTimeout(()=>{if(c.room===enemy.room&&enemy.hp>0)hit(enemy,c,10)},260+i*100)}}else if(m.type==='shield'&&c.room){if(c.shield>0)return;c.shield=3;broadcast(rooms.get(c.room),{type:'shield',id:c.id,blocks:3});}});ws.on('close',()=>{leave(c);clients.delete(c.id)});});
server.listen(PORT,()=>console.log('RNG PvP server on '+PORT));
